In [2]:
import numpy as np
arr = np.array([[10, 20, 30,40], [1,2,3,4]])
print(arr.size)
print(arr.ndim)
print(arr.shape)
print(arr.reshape(1,8))

8
2
(2, 4)
[[10 20 30 40  1  2  3  4]]


In [3]:
import numpy as np

arr = np.array([[1,6,7,8], [7,8,9,10]])
print(arr.transpose())

[[ 1  7]
 [ 6  8]
 [ 7  9]
 [ 8 10]]


In [4]:
import numpy as np
a = np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(np.add(a,b))

[ 6  8 10 12]


In [5]:
a = np.array([10,20,30])
b=np.array([30,20,10])
print(np.pow(a,b))

[ 5076944270305263616 -2101438300051996672      590490000000000]


In [6]:
import numpy as np
arr = np.array([[4,3,2],[10,1,0],[5,8,24]])
print(arr.var())
print(np.var(arr))

48.22222222222222
48.22222222222222


In [7]:
table = np.array([

[1,2,3],
[1,2,3],
[1,2,3],
[1,2,3],
[4,5,6],
[4,5,6],
[4,5,6]
])
print(np.percentile(table,50))

3.0


In [8]:
x = np.array(['Hello \n', 'World'])
y = np.array(['Welcome', 'Learners'])
result = np.char.add(x,y);
print(result)

['Hello \nWelcome' 'WorldLearners']


In [9]:
str = "Hello there, how are you, did you have your food?"
z= str.replace('there', 'Pawan').replace("food", "breakfast")
print(z)

Hello Pawan, how are you, did you have your breakfast?


In [10]:
str = "Hello there, how are you, did you have your food?"

dict = {'there': 'Pawan',
        'food': 'breakfast'
        }
for i,j in dict.items():
    str= np.char.replace(str,i,j)

print(str)



Hello Pawan, how are you, did you have your breakfast?


In [11]:
s1= "Hi, How are you"
print(np.char.upper(s1))
print(np.char.lower(s1))

HI, HOW ARE YOU
hi, how are you


In [12]:
import numpy as np

array_1d = np.array([1,2,3,4,5])
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
#first row
print(array_2d[0,:])
#first column
print(array_2d[:,0])
#third column
print(array_2d[:,2])
print

[1 2 3]
[1 4 7]
[3 6 9]


<function print(*args, sep=' ', end='\n', file=None, flush=False)>

In [13]:
# Scling
employee_rating = np.array([1, 4, 3, 5, 6, 8, 9, 10, 12])
print(employee_rating[1:7])

[4 3 5 6 8 9]


In [14]:
Books = np.array(['Physics', 'Data Science', 'Maths', 'Python', 'Hadoop', 'OOPS', 'Java', 'Cloud'])
print(Books[5:])

['OOPS' 'Java' 'Cloud']


In [15]:
X= np.array([8,7,6,5,4,3,2,1])
print(X[1:5:3])
# Slice using negative index
print(X[-7:-3:3])

[7 4]
[7 4]


In [16]:
import pandas as pd
data = [101,201,130,401,150,601,170,801,901]
s = pd.Series(data, index=['a','b','c','d','e','f','g','h','i']);


In [17]:
print(s.iloc[2:5])

c    130
d    401
e    150
dtype: int64


In [18]:
print(s.loc[['b','e', 'h']])

b    201
e    150
h    801
dtype: int64


In [19]:
print(s.loc[:'d'])

a    101
b    201
c    130
d    401
dtype: int64


In [20]:
print(s.iloc[:3])

a    101
b    201
c    130
dtype: int64


In [21]:
data_dict = {'Name': ['Alice', 'Bob', 'Charlie', ],
             'Age': [25, 30, 22],
             'Salary': [50000, 60000, 45000]}

In [22]:
data_list = [['Raj', 25, 50000],
             ['Ram', 30, 60000],
             ['Krish', 22, 45000]]
columns = ['Name', 'Age', 'Salary']
df_list = pd.DataFrame(data_list, columns)
print(df_list)
      

            0   1      2
Name      Raj  25  50000
Age       Ram  30  60000
Salary  Krish  22  45000


In [23]:
import pandas as pd
dfe = pd.read_excel('Iris.xlsx')
print(dfe.loc[2:3, ['sepal_length', 'petal_length']])

   sepal_length  petal_length
2           4.7           1.3
3           4.6           1.5


In [24]:
dfe_sepal_len = dfe['sepal_length'] > 5
dfe_petal_len = dfe['petal_length'] < 2
df_petal_width = dfe['petal_width'] < 0.4
print(dfe[dfe_sepal_len & dfe_petal_len & df_petal_width ])

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
10           5.4          3.7           1.5          0.2  setosa
14           5.8          4.0           1.2          0.2  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
46           5.1          3.8           1.6          0.2  setosa
48           5.3         

In [25]:
setosa_df = dfe[(dfe['species'] == 'setosa') & (dfe['sepal_length'] > 5)]
setosa_df


sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
10           5.4          3.7           1.5          0.2  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
23           5.1          3.3           1.7          0.5  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
44           5.1          3.8           1.9          0.4  setosa
46           5.1          3.8           1.6          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa

In [26]:
dfe['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [27]:
dfe['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [28]:
dfe.sort_values(by='sepal_length', ascending=False)

sepal_length  sepal_width  petal_length  petal_width    species
131           7.9          3.8           6.4          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
..            ...          ...           ...          ...        ...
41            4.5          2.3           1.3          0.3     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
13            4.3          3.0           1.1          0.1     setosa

[150 rows x 5 columns]

In [32]:
dfe.shape

(150, 5)

In [29]:
dfe.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [30]:
dfe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [31]:
dfe.groupby('species').mean()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa             5.006        3.418         1.464        0.244
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [36]:
df = pd.read_csv('HousePrices.csv')
df['price'].mean()

np.float64(551962.9884732141)